version: '3.7'

services:
  app:
    container_name: app
    build: .docker/app
    environment:
      - PHP_IDE_CONFIG=serverName=testRestAPI
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www
      - .docker/app/.bashrc:/home/www-data/.bashrc
      - .docker/app/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  nginx:
    container_name: nginx
    build: ./.docker/nginx
    volumes:
      - ./:/var/www
    ports:
      - 49100:80
    links:
      - app
  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
  redis_insight:
      image: redislabs/redisinsight:1.14.0
      container_name: redis_insight
      restart: always
      ports:
        - 8001:8001
      volumes:
        - redis_insight_volume_data:/db

volumes:
  redis_volume_data:
  redis_insight_volume_data: