imports:
    - { resource: parameters.yaml }


services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Infrastructure\Cache\CachedTodoServiceApi:
        class: App\Infrastructure\Cache\CachedTodoServiceApi
        arguments:
            $todosServiceApi: '@App\Infrastructure\HttpClientApi\TodoServiceApi'

    App\Application\Service\TodosServiceInterface:
        alias: App\Infrastructure\Cache\CachedTodoServiceApi

    App\Infrastructure\HttpClientApi\TodoServiceApi:
        arguments:
            $domain: '%domain.url%'
